---
# Github actions workflow file
name: magic_carpet_linting

on:  # yamllint disable rule:truthy
    push:
        branches:
            - main
            - feature/*
        paths-ignore:
            - 'README.md'
            - 'TODO.md'
    pull_request:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - 'TODO.md'

jobs:
    build:
        name: Lint and test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements-lint.txt
                pip freeze install
            - name: Execute black formatting check
              run: make black
            - name: Execute pylama check
              run: make pylama
            - name: Execute yamllint check
              run: make yamllint
            - name: Execute bandit check
              run: make bandit
            - name: Execute pytest (Github actions version)
              run: make pytest-gh-actions
